// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gitee.VisualStudio
{
    static class Vsix
    {
        public const string Id = "E1307109-9A20-4A1A-8788-B9B642193C47";
        public const string Name = "Gitee Extension for Visual Studio";
        public const string Description = @"A Visual Studio Extension that brings the Gitee Flow into Visual Studio.";
        public const string Language = "zh-CN";
        public const string Version = "1.0.71";
        public const string Author = "Gitee";
        public const string Tags = "Gitee;git;open source;source control;branch;pull request;team explorer;commit;publish";
    }
}
