// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gitee.VisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "B1077C66-1666-4F60-BDFA-BA078FDABCCE";
        public const string Name = "Gitee Extension for Visual Studio";
        public const string Description = @"A Visual Studio Extension that brings the Gitee Flow into Visual Studio.";
        public const string Language = "zh-CN";
        public const string Version = "1.0.87";
        public const string Author = "Gitee";
        public const string Tags = "Gitee;OSChina;Gitee.com;码云;开源中国;git;team explorer;commit";
    }
}
