// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gitee.VisualStudio
{
    static class Vsix
    {
        public const string Id = "B1077C66-1666-4F60-BDFA-BA078FDABCCE";
        public const string Name = "Gitee Extension for Visual Studio";
        public const string Description = @"A Visual Studio Extension that brings the Gitee Flow into Visual Studio.";
        public const string Language = "zh-CN";
        public const string Version = "1.0.0.5";
        public const string Author = "Gitee";
        public const string Tags = "Gitee;git;open source;source control;branch;pull request;team explorer;commit;publish";
    }
}
